version: "3.3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: idp
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./localhost.pem:/etc/x509/https/certfile.pem
      - ./localhost.key:/etc/x509/https/keyfile.pem
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --https-certificate-file=/etc/x509/https/certfile.pem --https-certificate-key-file=/etc/x509/https/keyfile.pem
